application: corney-and-barrow-wines 
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

handlers:
- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/handler.py
  login: admin

- url: /static
  static_dir: static

- url: /(getwines|sendemail)/?
  script: main.py
  login: admin

- url: .*
  script: main.py

